apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.react.name }}
spec:
  type: {{ .Values.react.service.type }}
  selector:             
    app: {{ .Values.react.name }}
  ports:
    - port: {{ .Values.react.service.port }}       
      targetPort: {{ .Values.react.container.port }}   
      nodePort: {{ .Values.react.service.nodePort }} 